apiVersion: app/v1
kind: Deployment
metadata:
  name: worker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service
  spec:
    containers:
      - name: worker-service
        image: femstuff/worker-service:latest
        env:
          - name: REDIS_ADDRESS
            value: "redis:6379"
          - name: RABBITMQ_URL
            value: "amqp://guest:guest@rabbitmq:5672/"